[package]
name = "wrpc-cli"
version = "0.8.0"
description = "wRPC CLI utilities"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tracing-subscriber = { workspace = true, features = [
    "ansi",
    "env-filter",
    "fmt",
    "smallvec",
    "tracing-log",
] }
zenoh = { workspace = true, optional = true, features = ["transport_tcp"] }
serde_json = { workspace = true, default-features = false }

[features]
default = ["zenoh-transport"]
zenoh-transport = ["dep:zenoh", "dep:tokio", "tokio/sync"]